# Generated by Django 5.1.7 on 2025-03-20 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("D", "Daily"),
                            ("W", "Weekly"),
                            ("BW", "Biweekly"),
                            ("M", "Monthly"),
                            ("SA", "Semiannually"),
                            ("A", "Annually"),
                            ("BA", "Biannually"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "savings_goal_table",
            },
        ),
        migrations.CreateModel(
            name="GoalPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="savings.savingsgoal",
                    ),
                ),
            ],
            options={
                "db_table": "goal_payment_table",
            },
        ),
    ]
