# Generated by Django 5.1.7 on 2025-03-19 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "recurring_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="expenses.recurring",
                    ),
                ),
            ],
            options={
                "db_table": "savings_goal_table",
            },
            bases=("expenses.recurring",),
        ),
        migrations.CreateModel(
            name="GoalPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="savings.savingsgoal",
                    ),
                ),
            ],
            options={
                "db_table": "goal_payment_table",
            },
        ),
    ]
