# Generated by Django 5.1.7 on 2025-04-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savingsgoal",
            old_name="goal_amount",
            new_name="payment_amount",
        ),
    ]
