# Generated by Django 5.1.7 on 2025-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetime",
            name="date_purchased",
            field=models.DateField(),
        ),
    ]
