# Generated by Django 4.2.18 on 2025-03-13 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0002_alter_expense_date_loan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "categories_table",
            },
        ),
        migrations.CreateModel(
            name="OneTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.CharField(max_length=50, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "one_times_table",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.CharField(max_length=50, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("O", "One Time"),
                            ("D", "Daily"),
                            ("W", "Weekly"),
                            ("M", "Monthly"),
                            ("A", "Annually"),
                            ("BW", "Biweekly"),
                        ],
                        default="O",
                        max_length=2,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_table",
            },
        ),
        migrations.RenameField(
            model_name="loan",
            old_name="start_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="principal",
        ),
        migrations.AddField(
            model_name="loan",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loan",
            name="description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="term_amt",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="loan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="loan",
            name="label",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="loan",
            name="term",
            field=models.CharField(
                choices=[("M", "Months"), ("Y", "Years")], default="M", max_length=1
            ),
        ),
        migrations.AlterModelTable(
            name="loan",
            table="loans_table",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.AddField(
            model_name="loan",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expenses.category",
            ),
        ),
    ]
