# Generated by Django 5.1.7 on 2025-03-19 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_category_onetime_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("O", "One Time"),
                    ("D", "Daily"),
                    ("W", "Weekly"),
                    ("M", "Monthly"),
                    ("A", "Annually"),
                    ("BW", "Biweekly"),
                ],
                default="O",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expenses.category",
            ),
        ),
        migrations.AlterField(
            model_name="onetime",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expenses.category",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expenses.category",
            ),
        ),
    ]
