# Generated by Django 4.2.18 on 2025-03-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountinfo", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
