# Generated by Django 4.2.18 on 2025-02-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
